version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
        - "5432:5152"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
        - my_dbdata:/var/lib/postgresql/data

  backend:
    image: promptflow  
    command: ["uvicorn", "promptflow.src.app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 8000:8000
    mem_limit: 3G

  worker:
    image: promptflow
    command: ["celery", "-A", "promptflow.src.tasks", "worker", "-l", "info"]
    mem_limit: 3G
  redis: 
    image: "redis:alpine"

volumes:
  my_dbdata:
