version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5515:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    volumes:
        - my_dbdata:/var/lib/postgresql/data

  backend:
    image: promptflow  
    command: ["uvicorn", "promptflow.src.app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    mem_limit: 3G
    depends_on:
      - db

  worker:
    image: promptflow
    command: ["celery", "-A", "promptflow.src.tasks", "worker", "-l", "info"]
    mem_limit: 3G
    environment:
      REDIS_URL: "redis://redis:6379/0" 
    depends_on:
      - redis

  redis: 
    image: "redis:alpine"

volumes:
  my_dbdata:
