version: '3.8'

services:
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - my_dbdata:/var/lib/postgresql/data

    backend:
        build: ./promptflow
        volumes:
        - ./promptflow:/app
        ports:
        - 8000:8000

    frontend:
        build: ./dashboard
        volumes:
        - ./dashboard:/usr/share/nginx/html
        ports:
        - 4200:80

    worker:
        build: ./promptflow/src
        volumes:
        - ./promptflow/src:/worker

    redis: 
        image: "redis:alpine"
volumes:
    my_dbdata:
